//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCatedra_PED_MR190768_GM172474_CM221954
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string email { get; set; }
        public Nullable<int> tipoUsuario { get; set; }
        public string contrasenia { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
    
        public virtual TipoUsuario TipoUsuario1 { get; set; }
    }
}
